/*
 Generated by typeshare 1.13.2
*/

export interface CreateRoom {
	username: string;
}

export interface CreateRoomResponse {
	room: string;
}

export interface JoinRoom {
	room: string;
	username: string;
}

export enum JoinRoomResponse {
	Success = "Success",
	NotFound = "NotFound",
	Full = "Full",
}

