/*
 Generated by typeshare 1.13.2
*/

export interface Auth {
	token: string;
}

export interface Card {
	index: string;
	name: string;
}

export interface Claims {
	sub: string;
	iat: number;
	exp: number;
}

export interface CreateRoom {
	username: string;
}

export interface CreateRoomResponse {
	room: string;
}

export interface Credentials {
	user_id: string;
	password: string;
}

export interface JoinRoom {
	room: string;
	username: string;
}

export enum CardType {
	Faith = "Faith",
	Order = "Order",
	Character = "Character",
}

export enum JoinRoomResponse {
	Success = "Success",
	NotFound = "NotFound",
	Full = "Full",
}

